//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Teacher
    {
        public int TeacherID { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Salary { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Position { get; set; }
        [Required(ErrorMessage = "Required")]
        public string CNIC { get; set; }
    } 
}
